#!/bin/bash

while [[ $# == 0 ]]
do
    echo ""
    echo "  Usage: water [command]"
    echo ""
    echo "      start       Boots the server in development mode"
    echo "      build       Rebuilds mithril into bundle.js"
    echo "      install     Installs python and node dependencies" 
    echo "      test        Runs server tests"
    echo ""
    break
done

# Parse argument
while [[ $# == 1 ]]
do
    arg="$1"
    case $arg in
        start)
            pushd client
            npm run watch &
            popd
            python server/app.py
            pkill -f node
            shift
            ;;
        build)
            pushd client
            npm run build
            shift
            ;; 
	install)
	    # client dependencies
	    pushd client
	    npm install
	    popd
	    # server dependences
	    pushd server
	    pip install -r requirements.txt
	    popd
	    shift
	    ;;
	test)
	    pushd server
	    source ./.envrc
	    nosetests --with-specplugin
	    popd
	    shift
	    ;;
    	*)
            echo "" 
            echo "  Argument '$arg' not recognized"
            ./water
            shift
            ;;
    esac
    break
done
